name: kyoumutechou
description: A simple boilerplate project
version: 1.0.0+1
publish_to: none

environment:
  sdk: '>=2.19.2 <3.0.0'

dependencies:
  flutter:
    sdk: flutter
  flutter_localizations:
    sdk: flutter

  cupertino_icons: ^1.0.6
  flutter_riverpod: ^2.4.6
  riverpod_annotation: ^2.3.1
  dio: ^5.3.3
  pretty_dio_logger: ^1.3.1


  google_fonts: ^6.1.0
  lottie: ^2.7.0
  connectivity_plus: ^5.0.1
  flutter_dotenv: ^5.1.0
  go_router: ^12.1.1
  easy_localization: ^3.0.3

  ## 設備
  camera: ^0.10.5+5
  google_ml_kit: ^0.16.3
  dropdown_search: ^5.0.6

  ## UI 
  flutter_native_splash: ^2.3.5
  lucide_icons: ^0.257.0
  transparent_image: ^2.0.1
  font_awesome_flutter: ^10.6.0
  auto_size_text: ^3.0.0
  pluto_grid: ^7.0.2

  ## Storage
  hive: ^2.2.3
  hive_flutter: ^1.1.0
  hive_generator: ^2.0.1

  ## i18n
  intl: ^0.18.1
  freezed_annotation: ^2.4.1


dev_dependencies:
  #flutter_test:
    #sdk: flutter
  json_serializable:
  go_router_builder: any
  build_runner: any
  build_verify: any
  flutter_gen_runner:
  freezed: ^2.2.1
  riverpod_generator: ^2.3.6
  import_sorter: ^4.6.0
  very_good_analysis: ^5.1.0

## Install derry from https://pub.dev/packages/derry and run derry build, derry watch, derry gen
scripts: derry.yaml

# https://pub.dev/packages/flutter_gen, after new assets run derry gen
flutter_gen:
  output: lib/gen/ # Optional (default: lib/gen/)

  #  integrations:
  #    flutter_svg: true
  #    flare_flutter: true

  assets:
    enabled: true
  fonts:
    enabled: true
  colors:
    enabled: true
    inputs:
      - assets/color/colors.xml
import_sorter:
  comments: false # Optional, defaults to true
  ignored_files: # Optional, defaults to []
    - \/lib\/*
flutter:
  uses-material-design: true
  generate: true
  assets:
    - assets/lang/en.json
    - assets/lang/ja.json
    - assets/env/.env.production
    - assets/env/.env.staging
    - assets/env/.env.development
    - assets/env/
    - assets/
    - assets/icons/
    - assets/images/
  fonts:
    - family: NotoSansJP
      fonts:
        - asset: assets/fonts/NotoSansJP-Black.ttf
        - asset: assets/fonts/NotoSansJP-Bold.ttf
        - asset: assets/fonts/NotoSansJP-ExtraBold.ttf
        - asset: assets/fonts/NotoSansJP-ExtraLight.ttf
        - asset: assets/fonts/NotoSansJP-Light.ttf
        - asset: assets/fonts/NotoSansJP-Medium.ttf
        - asset: assets/fonts/NotoSansJP-Regular.ttf
        - asset: assets/fonts/NotoSansJP-SemiBold.ttf
        - asset: assets/fonts/NotoSansJP-Thin.ttf

# dart run flutter_native_splash:create
# dart run flutter_native_splash:remove
flutter_native_splash:
  color: "#BFEEBB"
  image: assets/icons/koumu5.png